#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RANDOM_SEED": "00_model.ipynb",
         "logger": "00_model.ipynb",
         "GensimParameters": "00_model.ipynb",
         "generate_sentences_by_user": "00_model.ipynb",
         "EpochLogger": "00_model.ipynb",
         "Word2VecMovieRecommender": "00_model.ipynb"}

modules = ["model.py"]

git_url = "https://github.com/agacera/word2vec_movies_recommender/tree/master/"

def custom_doc_links(name): return None