#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RANDOM_SEED": "01_model.ipynb",
         "logger": "01_model.ipynb",
         "Recommendation": "00_core.ipynb",
         "Movie": "00_core.ipynb",
         "MovieRepository": "00_core.ipynb",
         "print_recommendations": "00_core.ipynb",
         "GensimParameters": "01_model.ipynb",
         "generate_sentences_by_user": "01_model.ipynb",
         "Word2VecMovieRecommender": "01_model.ipynb",
         "KnnRecommender": "01_model.ipynb"}

modules = ["core.py",
           "model.py"]

git_url = "https://github.com/agacera/udacity_mle_word2vec_recommender/tree/master/"

def custom_doc_links(name): return None