#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RANDOM_SEED": "00_core.ipynb",
         "logger": "02_recommender.ipynb",
         "Recommendation": "00_core.ipynb",
         "Movie": "00_core.ipynb",
         "MovieRepository": "00_core.ipynb",
         "print_recommendations": "00_core.ipynb",
         "GensimParameters": "01_model.ipynb",
         "generate_sentences_by_user": "01_model.ipynb",
         "Word2VecMovieModel": "01_model.ipynb",
         "hyper_parameter_tunning": "01_model.ipynb",
         "KnnRecommender": "02_recommender.ipynb",
         "load_api_key": "03_tmdb.ipynb",
         "MovieData": "03_tmdb.ipynb",
         "TmdbApi": "03_tmdb.ipynb",
         "create_dash_app": "04_dash.ipynb"}

modules = ["core.py",
           "model.py",
           "recommender.py",
           "tmdb.py",
           "dash.py"]

git_url = "https://github.com/agacera/udacity_mle_word2vec_recommender/tree/master/"

def custom_doc_links(name): return None